"""Add indexes to foreign keys for performance

Revision ID: 0bdaefd3e553
Revises: e6fd25d10f0a
Create Date: 2026-02-20 19:08:09.113996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bdaefd3e553'
down_revision = 'e6fd25d10f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtitles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subtitles_video_id'), ['video_id'], unique=False)

    with op.batch_alter_table('user_learning_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_learning_progress_subtitle_id'), ['subtitle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_learning_progress_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_series_id'), ['series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_source_url'), ['source_url'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_source_url'))
        batch_op.drop_index(batch_op.f('ix_videos_series_id'))

    with op.batch_alter_table('user_learning_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_learning_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_learning_progress_subtitle_id'))

    with op.batch_alter_table('subtitles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subtitles_video_id'))

    # ### end Alembic commands ###
