"""Initial migration with N-N categories and 1-N series

Revision ID: 15a565347f77
Revises: 
Create Date: 2026-02-20 16:39:57.250565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15a565347f77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('video_categories',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'category_id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('series_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('release_year', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('imdb_id'))
        batch_op.drop_index(batch_op.f('slug'))
        batch_op.drop_index(batch_op.f('youtube_id'))
        batch_op.create_index(batch_op.f('ix_videos_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_videos_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_view_count'), ['view_count'], unique=False)
        batch_op.drop_constraint(batch_op.f('videos_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('videos_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'series', ['series_id'], ['id'])
        batch_op.drop_column('imdb_id')
        batch_op.drop_column('added_by_user_id')
        batch_op.drop_column('youtube_id')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('youtube_id', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('added_by_user_id', mysql.VARCHAR(length=36), nullable=True))
        batch_op.add_column(sa.Column('imdb_id', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('videos_ibfk_1'), 'users', ['added_by_user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('videos_ibfk_2'), 'categories', ['category_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_videos_view_count'))
        batch_op.drop_index(batch_op.f('ix_videos_source_type'))
        batch_op.drop_index(batch_op.f('ix_videos_slug'))
        batch_op.drop_index(batch_op.f('ix_videos_level'))
        batch_op.create_index(batch_op.f('youtube_id'), ['youtube_id'], unique=True)
        batch_op.create_index(batch_op.f('slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('imdb_id'), ['imdb_id'], unique=True)
        batch_op.drop_column('release_year')
        batch_op.drop_column('series_id')
        batch_op.drop_column('tmdb_id')

    op.drop_table('video_categories')
    op.drop_table('series')
    # ### end Alembic commands ###
