"""add author and country to videos

Revision ID: 178b3a5fbabd
Revises: ddd8057b651a
Create Date: 2026-02-21 09:39:26.713663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178b3a5fbabd'
down_revision = 'ddd8057b651a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_videos_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_country'), ['country'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_country'))
        batch_op.drop_index(batch_op.f('ix_videos_author'))
        batch_op.drop_column('country')
        batch_op.drop_column('author')

    # ### end Alembic commands ###
