"""Added VideoReport and MovieRequest models

Revision ID: 1f0d24d77f46
Revises: a9420b8e2537
Create Date: 2026-03-02 08:36:34.235835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f0d24d77f46'
down_revision = 'a9420b8e2537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DONE', 'REJECTED'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movie_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movie_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_movie_requests_user_id'), ['user_id'], unique=False)

    op.create_table('video_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', 'IGNORED'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_reports_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_reports_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_reports_video_id'))
        batch_op.drop_index(batch_op.f('ix_video_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_video_reports_status'))

    op.drop_table('video_reports')
    with op.batch_alter_table('movie_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movie_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_movie_requests_status'))

    op.drop_table('movie_requests')
    # ### end Alembic commands ###
