"""Add AIAssessment model

Revision ID: 34b437216bbb
Revises: e1dd2c02b2ea
Create Date: 2026-03-14 19:40:15.389783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b437216bbb'
down_revision = 'e1dd2c02b2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('quiz_data', sa.JSON(), nullable=False),
    sa.Column('user_answers', sa.JSON(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('grammar_feedback', sa.Text(), nullable=True),
    sa.Column('vocab_feedback', sa.Text(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED'), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_assessments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_assessments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_assessments_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_assessments_status'))

    op.drop_table('ai_assessments')
    # ### end Alembic commands ###
