"""add slug in viddeo

Revision ID: 378a47357cf1
Revises: 2d9c0a6780ba
Create Date: 2026-02-07 18:51:54.107930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378a47357cf1'
down_revision = '2d9c0a6780ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
