"""add status and runtime fields, fix nullability

Revision ID: 7443c9dd33d0
Revises: 178b3a5fbabd
Create Date: 2026-02-22 12:22:51.466956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7443c9dd33d0'
down_revision = '178b3a5fbabd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('runtime', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('public', 'private'), nullable=False))
        batch_op.create_index(batch_op.f('ix_videos_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_status'))
        batch_op.drop_column('status')
        batch_op.drop_column('runtime')

    # ### end Alembic commands ###
