"""Add FlashcardExercise model

Revision ID: 74ffc1c40b86
Revises: 859bc22eb89b
Create Date: 2026-03-02 13:23:22.577374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ffc1c40b86'
down_revision = '859bc22eb89b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcard_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('quiz_data', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flashcard_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flashcard_exercises_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_flashcard_exercises_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flashcard_exercises_user_id'))
        batch_op.drop_index(batch_op.f('ix_flashcard_exercises_status'))

    op.drop_table('flashcard_exercises')
    # ### end Alembic commands ###
