"""add flashcards table

Revision ID: 859bc22eb89b
Revises: 1f0d24d77f46
Create Date: 2026-03-02 12:04:47.921598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859bc22eb89b'
down_revision = '1f0d24d77f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('context_sentence', sa.Text(), nullable=True),
    sa.Column('ipa', sa.String(length=100), nullable=True),
    sa.Column('pos', sa.String(length=50), nullable=True),
    sa.Column('definition_vi', sa.Text(), nullable=True),
    sa.Column('example_en', sa.Text(), nullable=True),
    sa.Column('example_vi', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flashcards_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flashcards_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flashcards_video_id'))
        batch_op.drop_index(batch_op.f('ix_flashcards_user_id'))

    op.drop_table('flashcards')
    # ### end Alembic commands ###
