"""Add user_answers to FlashcardExercise

Revision ID: b3e58ec040d4
Revises: 74ffc1c40b86
Create Date: 2026-03-02 13:56:07.926020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e58ec040d4'
down_revision = '74ffc1c40b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_answers', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard_exercises', schema=None) as batch_op:
        batch_op.drop_column('user_answers')

    # ### end Alembic commands ###
