"""Added SRS UserTagMastery table and UserKnowledgeState

Revision ID: ba8aac742142
Revises: c3d9e7a41f20
Create Date: 2026-04-18 15:41:14.904960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8aac742142'
down_revision = 'c3d9e7a41f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_knowledge_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('latent_state', sa.JSON(), nullable=True),
    sa.Column('interaction_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_knowledge_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_knowledge_states_user_id'), ['user_id'], unique=True)

    op.create_table('user_tag_masteries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=True),
    sa.Column('interval_days', sa.Float(), nullable=True),
    sa.Column('last_practiced_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tag_id', name='uq_user_tag_mastery')
    )
    with op.batch_alter_table('user_tag_masteries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_tag_masteries_tag_id'), ['tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_tag_masteries_user_id'), ['user_id'], unique=False)

    # Auto-generated drop indices commented out to prevent MySQL FK conflicts
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Auto-generated recreate indices commented out to prevent MySQL FK conflicts
    pass

    with op.batch_alter_table('user_tag_masteries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_tag_masteries_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_tag_masteries_tag_id'))

    op.drop_table('user_tag_masteries')
    with op.batch_alter_table('user_knowledge_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_knowledge_states_user_id'))

    op.drop_table('user_knowledge_states')
    # ### end Alembic commands ###
