"""Remove series and user learning progress references

Revision ID: d84e07b27add
Revises: 7443c9dd33d0
Create Date: 2026-02-22 15:48:36.668905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd84e07b27add'
down_revision = '7443c9dd33d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Xử lý bảng 'user_learning_progress' (là bảng con của 'subtitles' và 'users')
    print("Dropping foreign keys and table 'user_learning_progress'...")
    with op.batch_alter_table('user_learning_progress', schema=None) as batch_op:
        # Gỡ bỏ các Index
        batch_op.drop_index(batch_op.f('ix_user_learning_progress_subtitle_id'))
        batch_op.drop_index(batch_op.f('ix_user_learning_progress_user_id'))
        # Gỡ bỏ Foreign Keys
        batch_op.drop_constraint('user_learning_progress_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('user_learning_progress_ibfk_2', type_='foreignkey')
    op.drop_table('user_learning_progress')

    # 2. Xử lý bảng con 'videos' (gỡ bỏ liên kết tới 'series')
    print("Dropping foreign key and columns from 'videos'...")
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_series_id'))
        batch_op.drop_constraint('videos_ibfk_1', type_='foreignkey')
        batch_op.drop_column('series_id')
        batch_op.drop_column('episode_number')

    # 3. Xóa bảng cha 'series'
    print("Dropping table 'series'...")
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('slug'))
    op.drop_table('series')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('episode_number', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('series_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('videos_ibfk_1'), 'series', ['series_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_videos_series_id'), ['series_id'], unique=False)

    op.create_table('series',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('slug'), ['slug'], unique=True)

    op.create_table('user_learning_progress',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('subtitle_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('user_attempt_text', sa.Text(), nullable=True),
    sa.Column('score', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subtitle_id'], ['subtitles.id'], name=op.f('user_learning_progress_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_learning_progress_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user_learning_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_learning_progress_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_learning_progress_subtitle_id'), ['subtitle_id'], unique=False)

    # ### end Alembic commands ###
