"""add external movie columns

Revision ID: dae5e339f5ea
Revises: 378a47357cf1
Create Date: 2026-02-09 20:40:01.874179

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dae5e339f5ea'
down_revision = '378a47357cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imdb_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('stream_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('backdrop_url', sa.String(length=500), nullable=True))
        batch_op.alter_column('source_url',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
        batch_op.create_unique_constraint(None, ['imdb_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('source_url',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('backdrop_url')
        batch_op.drop_column('stream_url')
        batch_op.drop_column('imdb_id')

    # ### end Alembic commands ###
