"""Update Subtitle ID to BigInteger and add subtitle_vtt_url to Video

Revision ID: ddd8057b651a
Revises: 0bdaefd3e553
Create Date: 2026-02-20 19:27:10.206456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ddd8057b651a'
down_revision = '0bdaefd3e553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_learning_progress', schema=None) as batch_op:
        # Tạm thời xóa khóa ngoại để MySQL cho phép đổi kiểu dữ liệu
        batch_op.drop_constraint('user_learning_progress_ibfk_1', type_='foreignkey')
        batch_op.alter_column('subtitle_id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('subtitles', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('user_learning_progress', schema=None) as batch_op:
        # Tạo lại khóa ngoại sau khi cả 2 bảng đã lên BigInteger
        batch_op.create_foreign_key('user_learning_progress_ibfk_1', 'subtitles', ['subtitle_id'], ['id'])

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle_vtt_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('subtitle_vtt_url')

    with op.batch_alter_table('user_learning_progress', schema=None) as batch_op:
        batch_op.alter_column('subtitle_id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('subtitles', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
