"""add progress tracking to watch history

Revision ID: e1dd2c02b2ea
Revises: f85d60931241
Create Date: 2026-03-14 16:32:00.190512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1dd2c02b2ea'
down_revision = 'f85d60931241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_position', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_history', schema=None) as batch_op:
        batch_op.drop_column('duration')
        batch_op.drop_column('last_position')

    # ### end Alembic commands ###
