"""Add GrammarTag and Subtitle cloze_data

Revision ID: e8cf082efcf3
Revises: ba8aac742142
Create Date: 2026-04-18 22:31:09.198666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8cf082efcf3'
down_revision = 'ba8aac742142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_vi', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grammar_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grammar_tags_name_en'), ['name_en'], unique=False)

    # Seed Grammar Tags (Bổ sung dữ liệu mồi ngay trong migration để ko bị lỗi Integrity)
    grammar_data = [
        (0, "future", "Thì tương lai đơn"),
        (1, "future continuous", "Thì tương lai tiếp diễn"),
        (2, "future perfect", "Thì tương lai hoàn thành"),
        (3, "future perfect continuous", "Thì tương lai hoàn thành tiếp diễn"),
        (4, "past", "Thì quá khứ đơn"),
        (5, "past continuous", "Thì quá khứ tiếp diễn"),
        (6, "past perfect", "Thì quá khứ hoàn thành"),
        (7, "past perfect continuous", "Thì quá khứ hoàn thành tiếp diễn"),
        (8, "present", "Thì hiện tại đơn"),
        (9, "present continuous", "Thì hiện tại tiếp diễn"),
        (10, "present perfect", "Thì hiện tại hoàn thành"),
        (11, "present perfect continuous", "Thì hiện tại hoàn thành tiếp diễn"),
    ]
    for gid, en, vi in grammar_data:
        op.execute(f"INSERT INTO grammar_tags (id, name_en, name_vi) VALUES ({gid}, '{en}', '{vi}')")

    # Dọn dẹp dữ liệu cũ bị lỗi trong user_tag_masteries (ID không nằm trong 0-11)
    op.execute("DELETE FROM user_tag_masteries WHERE tag_id NOT BETWEEN 0 AND 11")

    # with op.batch_alter_table('movie_ai_analyses', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('ix_movie_ai_analyses_video_id'))
    #     batch_op.create_index(batch_op.f('ix_movie_ai_analyses_video_id'), ['video_id'], unique=True)

    with op.batch_alter_table('movie_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movie_requests_status_created_at'))

    with op.batch_alter_table('subtitles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grammar_tag_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cloze_data', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_subtitles_grammar_tag_id'), ['grammar_tag_id'], unique=False)
        batch_op.create_foreign_key(None, 'grammar_tags', ['grammar_tag_id'], ['id'])

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profile_is_online'))

    with op.batch_alter_table('user_tag_masteries', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'grammar_tags', ['tag_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    with op.batch_alter_table('video_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_reports_status_created_at'))

    with op.batch_alter_table('watch_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watch_history_watched_at'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watch_history_watched_at'), ['watched_at'], unique=False)

    with op.batch_alter_table('video_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_reports_status_created_at'), ['status', 'created_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('user_tag_masteries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profile_is_online'), ['is_online'], unique=False)

    with op.batch_alter_table('subtitles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_subtitles_grammar_tag_id'))
        batch_op.drop_column('cloze_data')
        batch_op.drop_column('grammar_tag_id')

    with op.batch_alter_table('movie_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movie_requests_status_created_at'), ['status', 'created_at'], unique=False)

    with op.batch_alter_table('movie_ai_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movie_ai_analyses_video_id'))
        batch_op.create_index(batch_op.f('ix_movie_ai_analyses_video_id'), ['video_id'], unique=False)

    with op.batch_alter_table('grammar_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grammar_tags_name_en'))

    op.drop_table('grammar_tags')
    # ### end Alembic commands ###
