"""Added WatchHistory, StudyRoadmap, DailyTask

Revision ID: f85d60931241
Revises: af217357573d
Create Date: 2026-03-14 15:53:43.216771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f85d60931241'
down_revision = 'af217357573d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('current_score', sa.Float(), nullable=False),
    sa.Column('target_score', sa.Float(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('blueprint_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_roadmaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_roadmaps_user_id'), ['user_id'], unique=False)

    op.create_table('watch_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('watched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watch_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watch_history_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watch_history_video_id'), ['video_id'], unique=False)

    op.create_table('daily_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('task_detail_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'done'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['study_roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_tasks_roadmap_id'), ['roadmap_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_tasks_roadmap_id'))

    op.drop_table('daily_tasks')
    with op.batch_alter_table('watch_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watch_history_video_id'))
        batch_op.drop_index(batch_op.f('ix_watch_history_user_id'))

    op.drop_table('watch_history')
    with op.batch_alter_table('study_roadmaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_roadmaps_user_id'))

    op.drop_table('study_roadmaps')
    # ### end Alembic commands ###
